import express from "express";
import nodemailer from "nodemailer";
import cors from "cors";
import dotenv from "dotenv";

dotenv.config();

const app = express();
app.use(cors());
app.use(express.json());

// ✅ DEBUG: check env loaded
console.log("EMAIL:", process.env.EMAIL);
console.log("PASS:", process.env.PASS ? "Loaded ✅" : "NOT LOADED ❌");

// ✅ Mail transporter (MORE RELIABLE CONFIG)
const transporter = nodemailer.createTransport({
  host: "smtp.gmail.com",
  port: 587,
  secure: false, // TLS
  auth: {
    user: process.env.EMAIL,
    pass: process.env.PASS,
  },
});

// ✅ VERIFY CONNECTION (VERY IMPORTANT)
transporter.verify((error, success) => {
  if (error) {
    console.error("❌ SMTP ERROR:", error);
  } else {
    console.log("✅ SMTP Ready to send emails");
  }
});

// ✅ TEST ROUTE
app.get("/", (req, res) => {
  res.send("Email service running ✅");
});

// ✅ MAIN ALERT ROUTE
app.post("/send-alert", async (req, res) => {
  const { email, type, confidence, name, address } = req.body;

  console.log("📩 Incoming request:", req.body);

  try {
    const info = await transporter.sendMail({
      from: `"Deepfake Guard" <${process.env.EMAIL}>`,
      to: email,
      subject: `🚨 Deepfake Alert - ${type}`,
      html: `
        <div style="background:#0e1117;padding:20px;color:white;font-family:Arial;">
          <h2 style="color:#ff4b4b;">🚨 Deepfake Alert Detected</h2>

          <hr style="border:1px solid #30363d;margin:15px 0;" />

          <p><b>Name:</b> ${name || "Unknown"}</p>

          <p><b>Status:</b> 
            <span style="color:${type === "FAKE" ? "#ff4b4b" : "#22c55e"};">
              ${type}
            </span>
          </p>

          <p><b>Confidence:</b> ${Math.round(confidence || 0)}%</p>

          <p><b>Address:</b> ${address || "Not Available"}</p>

          <hr style="border:1px solid #30363d;margin:15px 0;" />

          <p style="font-size:12px;color:#888;">
            This alert was generated by Deepfake Guard Security System
          </p>
        </div>
      `,
    });

    console.log("✅ Email sent:", info.response);

    res.json({ success: true });

  } catch (err) {
    console.error("❌ Email Error:", err);
    res.status(500).json({ error: "Email failed", details: err.message });
  }
});

// ✅ START SERVER
const PORT = process.env.PORT || 5000;

app.listen(PORT, () => {
  console.log(`🚀 Email service running on port ${PORT}`);
});